exp_premerge_smoke_rgbd_orbslam2:
  Config: premerge-smoke/config_premerge_smoke_rgbd.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: rgbd, rgb_max: 200, rgb_step: 3}
  Module: orbslam2

exp_premerge_smoke_rgbd_droidslam:
  Config: premerge-smoke/config_premerge_smoke_rgbd.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: rgbd, rgb_max: 200, rgb_step: 3}
  Module: droidslam
