exp_premerge_smoke_stereo_orbslam2:
  Config: premerge-smoke/config_premerge_smoke_stereo.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_max: 200, rgb_step: 3}
  Module: orbslam2

exp_premerge_smoke_stereo_droidslam:
  Config: premerge-smoke/config_premerge_smoke_stereo.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_max: 200, rgb_step: 3}
  Module: droidslam
