eth:
- cables_1
- desk_3
- large_loop_1
- mannequin_1
- mannequin_3
- mannequin_4
- mannequin_5
- planar_2
- planar_3
- plant_scene_1
- plant_scene_2
- plant_scene_3
- repetitive
- sfm_bench
- sofa_1
- sofa_2
- sofa_3
- sofa_4
- table_3
- table_4
- table_7
- vicon_light_1
- vicon_light_2
