# eth:
# - 'table_3'

rgbdtum:
# Easy / Short Sequences
- 'rgbd_dataset_freiburg1_xyz'
- 'rgbd_dataset_freiburg3_structure_texture_far'
- 'rgbd_dataset_freiburg3_structure_texture_near'
# Easy / Long Sequences
- 'rgbd_dataset_freiburg2_xyz'
- 'rgbd_dataset_freiburg2_desk'
- 'rgbd_dataset_freiburg3_nostructure_texture_near_withloop'
- 'rgbd_dataset_freiburg3_long_office_household'
# Medium / Short Sequences
- 'rgbd_dataset_freiburg1_desk'







