exp_debug_allfeature-dev:
  Config: config_debug.yaml
  NumRuns: 1
  Parameters: {verbose: 1, segmentation: mask2former, rgb_idx: [2000,21102], mode: rgbd, depth: fastfoundationstereo}

  Module: allfeature-dev

































# exp_colmap_01:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 1000 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_02:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 800 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_03:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 600 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_04:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 400 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_05:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 200 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_06:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 100 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_07:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 80 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_08:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_vpr: 40 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap

# exp_colmap_09:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_vpr: 35 ,'mapper_type': 'colmap', 'matching_type': 'sift_bruteforce'}
#   Module: colmap