exp_train_droid_droid_pth:
  Config: config_train_droid.yaml
  Module: droidslam-dev
  NumRuns: 3
  Parameters:
    mode: mono
    upsample: 0
    verbose: 0
    weights: droid.pth

exp_train_droid_test_pth:
  Config: config_train_droid.yaml
  Module: droidslam-dev
  NumRuns: 3
  Parameters:
    mode: mono
    upsample: 0
    verbose: 0
    weights: test.pth