# exp_allfeature_mono:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, mode: mono}
#   Module: allfeature-dev

exp_allfeature_rgbd:
  Config: config_vslamlabbench.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: rgbd}
  Module: allfeature-dev
