# exp_test_colmap:
#   Config: config_sfm.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: colmap

# exp_test_glomap:
#   Config: config_sfm.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: glomap

# exp_test_gensfm:
#   Config: config_sfm.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: gensfm-dev

exp_test_mast3r:
  Config: config_sfm.yaml
  NumRuns: 1
  Parameters: {verbose: 1}
  Module: mast3r-dev

# exp_test_vggt:
#   Config: config_sfm.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: vggt-dev