exp_allfeature_mono:
  Config: config_vslamlabbench.yaml
  NumRuns: 3
  Parameters: {verbose: 0, mode: mono}
  Module: allfeature-dev

# exp_allfeature_orbslam2_mono:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, mode: mono}
#   Module: orbslam2

# exp_allfeature_droidslam_mono:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, mode: mono}
#   Module: droidslam

