test_exp_vggt:
  Config: test_config_vggtslam.yaml
  NumRuns: 1
  Parameters: {verbose: 0, mode: mono}
  Module: vggt

test_exp_vggt_bf16:
  Config: test_config_vggtslam.yaml
  NumRuns: 1
  Parameters: {verbose: 0, mode: mono, precision: bf16, rgb_max: 80}
  Module: vggt
