test_exp_monotum_droidslam:
  Config: test_config_monotum.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_max: 200, rgb_step: 3}
  Module: droidslam

test_exp_monotum_colmap:
  Config: test_config_monotum.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_max: 200, rgb_step: 3}
  Module: colmap
