test_exp_hamlyn_mono_dpvo:
  Config: test_config_hamlyn.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_idx: [0,2000]}
  Module: dpvo

test_exp_hamlyn_rgbd_droidslam:
  Config: test_config_hamlyn.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: rgbd, rgb_idx: [0,2000]}
  Module: droidslam

test_exp_hamlyn_stereo_droidslam:
  Config: test_config_hamlyn.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_idx: [0,2000]}
  Module: droidslam

test_exp_hamlyn_stereo_orbslam3:
  Config: test_config_hamlyn.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_idx: [0,2000]}
  Module: orbslam3
