test_exp_malaga_mono_droidslam:
  Config: test_config_malaga.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_idx: [0,2000]}
  Module: droidslam

test_exp_malaga_stereo_orbslam3:
  Config: test_config_malaga.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_idx: [0,2000]}
  Module: orbslam3

test_exp_malaga_stereo_droidslam:
  Config: test_config_malaga.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_idx: [0,2000]}
  Module: droidslam
