test_exp_pamir-rig_dpvo:
  Config: test_config_pamir-rig.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_idx: [0,2000]}
  Module: dpvo

test_exp_pamir-rig_orbslam3_mono-vi:
  Config: test_config_pamir-rig.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono-vi, rgb_idx: [0,2000]}
  Module: orbslam3

test_exp_pamir-rig_droidslam:
  Config: test_config_pamir-rig.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo, rgb_idx: [0,2000]}
  Module: droidslam

test_exp_pamir-rig_orbslam3_stereo-vi:
  Config: test_config_pamir-rig.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo-vi, rgb_idx: [0,2000]}
  Module: orbslam3
