test_exp_hilti2026_mono_droidslam:
  Config: test_config_hilti2026.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_idx: [0,2000]}
  Module: droidslam

test_exp_hilti2026_mono_orbslam3:
  Config: test_config_hilti2026.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono, rgb_idx: [0,2000]}
  Module: orbslam3

test_exp_hilti2026_monovi_okvis2:
  Config: test_config_hilti2026.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono-vi, rgb_idx: [0,2000]}
  Module: okvis2
